name: barlow_twins
forward: barlow_twins_forward
requires_vit: false

transforms:
  type: multiview
  num_views: 2

projector:
  hidden_dim: 8192
  output_dim: 8192

loss:
  lambda_coeff: 0.0051

batch_sizes:
  default: 1024
  cifar10: 2048
  cifar100: 2048
  svhn: 2048
  stl10: 1024
  flowers102: 1024
  food101: 1024
  dtd: 1024
  cub200: 512
  tinyimagenet: 1024
  imagenet: 1024

optimizer:
  type: LARS
  lr: 5.0
  weight_decay: 1e-6

scheduler:
  type: LinearWarmupCosineAnnealing
