name: barlow_twins
forward: barlow_twins_forward

transforms:
  type: multiview
  num_views: 2

projector:
  hidden_dim: 2048
  output_dim: 2048

loss:
  lambda_coeff: 0.005


params:
  default:
    batch_size: 256
    max_epochs: 200
  # CIFAR-scale (32x32)
  cifar10:
    batch_size: 256
    max_epochs: 200
  cifar100:
    batch_size: 256
    max_epochs: 200
  svhn:
    batch_size: 256
    max_epochs: 200
  # Grayscale 28x28
  fashionmnist:
    batch_size: 256
    max_epochs: 200
  emnist:
    batch_size: 256
    max_epochs: 200
  kmnist:
    batch_size: 256
    max_epochs: 200
  notmnist:
    batch_size: 256
    max_epochs: 300
  medmnist:
    batch_size: 256
    max_epochs: 200
  # Other small datasets
  hasyv2:
    batch_size: 256
    max_epochs: 200
  arabiccharacters:
    batch_size: 256
    max_epochs: 400
  arabicdigits:
    batch_size: 256
    max_epochs: 400
  # Larger resolution
  stl10:
    batch_size: 256
    max_epochs: 200
  # Small fine-grained
  flowers102:
    batch_size: 256
    max_epochs: 400
  cub200:
    batch_size: 256
    max_epochs: 400
  dtd:
    batch_size: 256
    max_epochs: 400
  country211:
    batch_size: 256
    max_epochs: 200
  rockpaperscissor:
    batch_size: 256
    max_epochs: 400
  facepointing:
    batch_size: 256
    max_epochs: 300
  # Large datasets
  food101:
    batch_size: 256
    max_epochs: 200
  tinyimagenet:
    batch_size: 256
    max_epochs: 200
  imagenet:
    batch_size: 256
    max_epochs: 100

vit_optimizer:
  type: AdamW
  lr: 1.5e-4
  weight_decay: 0.05
  betas: [0.9, 0.999]

scheduler:
  type: LinearWarmupCosineAnnealing
