name: barlow_twins
forward: barlow_twins_forward
requires_vit: false

transforms:
  type: multiview
  num_views: 2

projector:
  hidden_dim: 8192
  output_dim: 8192

loss:
  lambda_coeff: 0.0051

batch_sizes:
  default: 256
  cifar10: 512
  cifar100: 512
  svhn: 512
  stl10: 256
  flowers102: 256
  food101: 128
  dtd: 256
  cub200: 128
  tinyimagenet: 128
  imagenet: 128

optimizer:
  type: LARS
  lr: 5.0
  weight_decay: 1e-6

scheduler:
  type: LinearWarmupCosineAnnealing
