name: barlow_twins
forward: barlow_twins_forward
requires_vit: false

transforms:
  type: multiview
  num_views: 2

projector:
  hidden_dim: 2048
  output_dim: 2048

loss:
  lambda_coeff: 0.0051

params:
  default:
    batch_size: 1024
    max_epochs: 200
  cifar10:
    batch_size: 2048
    max_epochs: 200
  cifar100:
    batch_size: 2048
    max_epochs: 200
  svhn:
    batch_size: 2048
    max_epochs: 200
  stl10:
    batch_size: 1024
    max_epochs: 200
  flowers102:
    batch_size: 1024
    max_epochs: 200
  food101:
    batch_size: 1024
    max_epochs: 200
  dtd:
    batch_size: 1024
    max_epochs: 200
  cub200:
    batch_size: 512
    max_epochs: 200
  tinyimagenet:
    batch_size: 1024
    max_epochs: 200
  imagenet:
    batch_size: 1024
    max_epochs: 100

resnet_optimizer:
  type: LARS
  lr: 1.6
  weight_decay: 1e-6

vit_optimizer:
  type: AdamW
  lr: 3e-4
  weight_decay: 0.05
  betas: [0.9, 0.999]

scheduler:
  type: LinearWarmupCosineAnnealing
