name: dino

transforms:
  type: multicrop
  num_global: 2
  num_local: 6

projector:
  hidden_dim: 2048
  bottleneck_dim: 256
  output_dim: 65536

loss:
  temperature_student: 0.1
  temperature_teacher: 0.04
  warmup_temperature_teacher: 0.04
  warmup_epochs_temperature_teacher: 30

momentum_teacher: 0.996


params:
  default:
    batch_size: 256
    max_epochs: 125
  # CIFAR-scale (32x32)
  cifar10:
    batch_size: 256
    max_epochs: 250
  cifar100:
    batch_size: 256
    max_epochs: 250
  svhn:
    batch_size: 256
    max_epochs: 188
  # Grayscale 28x28
  fashionmnist:
    batch_size: 256
    max_epochs: 188
  emnist:
    batch_size: 256
    max_epochs: 188
  kmnist:
    batch_size: 256
    max_epochs: 188
  notmnist:
    batch_size: 256
    max_epochs: 250
  medmnist:
    batch_size: 256
    max_epochs: 250
  # Other small datasets
  hasyv2:
    batch_size: 256
    max_epochs: 188
  arabiccharacters:
    batch_size: 256
    max_epochs: 313
  arabicdigits:
    batch_size: 256
    max_epochs: 313
  # Larger resolution
  stl10:
    batch_size: 256
    max_epochs: 188
  # Small fine-grained
  flowers102:
    batch_size: 256
    max_epochs: 375
  cub200:
    batch_size: 256
    max_epochs: 375
  dtd:
    batch_size: 256
    max_epochs: 375
  country211:
    batch_size: 256
    max_epochs: 250
  rockpaperscissor:
    batch_size: 256
    max_epochs: 375
  facepointing:
    batch_size: 256
    max_epochs: 250
  # Large datasets
  food101:
    batch_size: 256
    max_epochs: 125
  tinyimagenet:
    batch_size: 256
    max_epochs: 125
  imagenet:
    batch_size: 256
    max_epochs: 63

vit_optimizer:
  type: AdamW
  lr: 5e-4
  weight_decay: 0.05
  betas: [0.9, 0.999]

scheduler:
  type: LinearWarmupCosineAnnealing
