name: dino
requires_vit: true

transforms:
  type: multicrop
  num_global: 2
  num_local: 6

projector:
  hidden_dim: 2048
  bottleneck_dim: 256
  output_dim: 65536

loss:
  temperature_student: 0.1
  temperature_teacher: 0.04
  warmup_temperature_teacher: 0.04
  warmup_epochs_temperature_teacher: 30

momentum_teacher: 0.996

batch_sizes:
  default: 64
  cifar10: 128
  cifar100: 128
  svhn: 128
  stl10: 64
  flowers102: 64
  food101: 64
  dtd: 64
  cub200: 64
  tinyimagenet: 64
  imagenet: 64

optimizer:
  type: AdamW
  lr: 5e-4
  weight_decay: 0.04

scheduler:
  type: LinearWarmupCosineAnnealing
