name: lejepa
forward: lejepa_forward
requires_vit: false

transforms:
  type: multiview
  num_views: 4

projector:
  hidden_dim: 2048
  output_dim: 128

loss:
  lamb: 0.02
  t_max: 3.0
  n_points: 17
  num_slices: 256

batch_sizes:
  default: 128
  cifar10: 256
  cifar100: 256
  svhn: 256
  stl10: 128
  flowers102: 128
  food101: 128
  dtd: 128
  cub200: 128
  tinyimagenet: 128
  imagenet: 128

optimizer:
  type: LARS
  lr: 5.0
  weight_decay: 1e-6

scheduler:
  type: LinearWarmupCosineAnnealing
