name: lejepa
forward: lejepa_forward
requires_vit: false

transforms:
  type: multiview
  num_views: 4

projector:
  hidden_dim: 2048
  output_dim: 128

loss:
  lamb: 0.02
  t_max: 3.0
  n_points: 17
  num_slices: 256

batch_sizes:
  default: 1024
  cifar10: 2048
  cifar100: 2048
  svhn: 2048
  stl10: 1024
  flowers102: 1024
  food101: 1024
  dtd: 1024
  cub200: 512
  tinyimagenet: 1024
  imagenet: 1024

optimizer:
  type: LARS
  lr: 5.0
  weight_decay: 1e-6

scheduler:
  type: LinearWarmupCosineAnnealing
