name: mae
requires_vit: true

transforms:
  type: single

mask_ratio: 0.75

decoder:
  embed_dim: 512
  depth: 8
  num_heads: 16

batch_sizes:
  default: 256
  cifar10: 512
  cifar100: 512
  svhn: 512
  stl10: 256
  flowers102: 256
  food101: 256
  dtd: 256
  cub200: 256
  tinyimagenet: 256
  imagenet: 256

optimizer:
  type: AdamW
  lr: 1.5e-4
  weight_decay: 0.05
  betas: [0.9, 0.95]

scheduler:
  type: LinearWarmupCosineAnnealing
