name: nnclr
forward: nnclr_forward
requires_vit: false

transforms:
  type: multiview
  num_views: 2

projector:
  hidden_dim: 2048
  output_dim: 256

predictor:
  hidden_dim: 4096
  output_dim: 256

loss:
  temperature: 0.15

queue_size: 65536

batch_sizes:
  default: 256
  cifar10: 512
  cifar100: 512
  svhn: 512
  stl10: 256
  flowers102: 256
  food101: 256
  dtd: 256
  cub200: 128
  tinyimagenet: 256
  imagenet: 256

optimizer:
  type: LARS
  lr: 5.0
  weight_decay: 1e-6

scheduler:
  type: LinearWarmupCosineAnnealing
